#!/usr/bin/env python3
import os
import argparse
from subprocess import call

HOME = os.environ["HOME"] + "/"
CWD = os.getcwd()
DOTFILES = HOME + ".dotfiles/"

ignored = [
    ".git",
    "dotfiles",
]


def install():
    for i, file in enumerate(listFiles(DOTFILES)):
        print("[" + str(i) + "] " + HOME + file)
        createPath(HOME + file)
        if not createSymlink(HOME + file, DOTFILES + file):
            print("Aborted. Remaining files were not linked.")
            return False


def add(path: str):
    print(path)
    path = os.path.abspath(path)[len(HOME) :]
    print(path)
    if os.path.isfile(HOME + path):
        addFile(path)
    elif os.path.isdir(path):
        for file in listFiles(path):
            addFile(file)
    else:
        print("ERROR: " + path + " does not exist")
        return False


def rm(path: str):
    print("TODO")


def createPath(path):
    directories = path.split("/")
    dirstring = ""
    for directory in directories[:-1]:
        dirstring += directory + "/"
        if not os.path.isdir(dirstring):
            if not os.path.exists(dirstring):
                print("  Creating directory " + dirstring)
                os.mkdir(dirstring)
            else:
                print("Error: " + dirstring + " is a file. Expected a directory.")


def listFiles(path, basepath=None):
    files = []
    basepath = basepath or path
    for file in os.listdir(path):
        # Skip files in the ignored list
        if (path + "/" + file)[len(basepath) + 1 :] in ignored:
            continue
        # Add files to our list
        if os.path.isfile(path + "/" + file):
            files.append((path + "/" + file)[len(basepath) + 1 :])
        # Recursively check directories
        elif os.path.isdir(path + "/" + file):
            files = files + listFiles(path + "/" + file, basepath=basepath)
    return files


def addFile(path):
    homepath = HOME + path
    dfpath = DOTFILES + path
    createPath(dfpath)
    call(["mv", homepath, dfpath])
    call(["ln", "-s", dfpath, homepath])


def prompt(question, options):
    for key, label in options:
        print("    [" + key + "] " + label)
    keys = "/".join([key for key, _ in options])
    while True:
        try:
            answer = input("  " + question + " (" + keys + ") ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            print()
            return options[-1][0]
        for key, _ in options:
            if answer == key:
                return key
        print("  Not an option: " + answer)


def backupPath(path):
    backup = path + ".bak"
    i = 1
    while os.path.lexists(backup):
        backup = path + ".bak." + str(i)
        i += 1
    print("  Backing up " + path + " to " + backup)
    call(["mv", path, backup])


# Returns False if the user chose to abort, True otherwise
def createSymlink(path, source):
    if os.path.lexists(path):
        if os.path.islink(path) and os.path.realpath(path) == os.path.realpath(source):
            print("  Already linked")
            return True
        print("  " + path + " already exists")
        choice = prompt(
            "What would you like to do?",
            [
                ("b", "Back up the existing file and continue"),
                ("s", "Skip this file"),
                ("a", "Abort the install"),
            ],
        )
        if choice == "a":
            return False
        if choice == "s":
            print("  Skipping " + path)
            return True
        backupPath(path)
    call(["ln", "-s", source, path])
    return True


if __name__ == "__main__":
    parser = argparse.ArgumentParser(prog="Dotfiles")
    subparsers = parser.add_subparsers(dest="command")
    install_parser = subparsers.add_parser("install")
    add_parser = subparsers.add_parser("add")
    add_parser.add_argument("path")
    rm_parser = subparsers.add_parser("rm")
    rm_parser.add_argument("path")
    args = parser.parse_args()

    if args.command == "install":
        install()
    elif args.command == "add":
        add(args.path)
    elif args.command == "rm":
        rm(args.path)
    else:
        parser.print_help()
