return {
	bashls = {},
	beancount = require("lsp.beancount"),
	cssls = {},
	efm = require("lsp.efm"),
	eslint = {},
	gopls = {},
	html = {},
	jsonls = {},
	pyright = require("lsp.pyright"),
	rust_analyzer = {},
	sumneko_lua = require("lsp.sumneko_lua"),
	svelte = {},
	tsserver = require("lsp.tsserver"),
}
