return {
	bashls = {},
	beancount = require("lsp.beancount"),
	cssls = { ensure_installed = true },
	efm = require("lsp.efm"),
	eslint = {},
	gopls = { ensure_installed = true },
	html = { ensure_installed = true },
	jsonls = { ensure_installed = true },
	pyright = require("lsp.pyright"),
	rust_analyzer = {},
	sumneko_lua = require("lsp.sumneko_lua"),
	svelte = {},
	taplo = {},
	tsserver = require("lsp.tsserver"),
}
